<?php
namespace App\Units\Home\Providers;

use Car7axo\Laravel\Support\Unit\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'App\\Units\\Home\\Http\\Controllers';

    public function namespace(string $value)
    {
        parent::namespace($value); // TODO: Change the autogenerated stub
    }

//    public function getNamespace(): string
//    {
//        return 'App\\Units\\Home\\Http\\Controllers';
//    }
}
